=== hackilin/LMSGI03/datos.dtd
<!ELEMENT equipos (equipo)*>
<!ELEMENT equipo (nombre|ganados|perdidos|empatados|puntos)*>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ganados (#PCDATA)>
<!ELEMENT perdidos (#PCDATA)>
<!ELEMENT empatados (#PCDATA)>
<!ELEMENT puntos (#PCDATA)>

=== hackilin/LMSGI03/equipos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos SYSTEM "datos.dtd">
<equipos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquema.xsd">
<equipo>
  <nombre>FC Barcelona</nombre>
  <ganados>15</ganados>
  <perdidos>2</perdidos>
  <empatados>5</empatados>
  <puntos>50</puntos>
</equipo>
<equipo>
  <nombre>At.Madrid</nombre>
  <ganados>12</ganados>
  <perdidos>2</perdidos>
  <empatados>8</empatados>
  <puntos>44</puntos>
</equipo>
<equipo>
  <nombre>Real Madrid</nombre>
  <ganados>13</ganados>
  <perdidos>6</perdidos>
  <empatados>3</empatados>
  <puntos>42</puntos>
</equipo>
<equipo>
  <nombre>Sevilla</nombre>
  <ganados>10</ganados>
  <perdidos>6</perdidos>
  <empatados>6</empatados>
  <puntos>36</puntos>
</equipo>
<equipo>
  <nombre>Getafe</nombre>
  <ganados>8</ganados>
  <perdidos>6</perdidos>
  <empatados>8</empatados>
  <puntos>32</puntos>
</equipo>
<equipo>
  <nombre>Betis</nombre>
  <ganados>9</ganados>
  <perdidos>8</perdidos>
  <empatados>5</empatados>
  <puntos>32</puntos>
</equipo>
<equipo>
  <nombre>Alaves</nombre>
  <ganados>9</ganados>
  <perdidos>8</perdidos>
  <empatados>5</empatados>
  <puntos>30</puntos>
</equipo>
<equipo>
  <nombre>Valencia</nombre>
  <ganados>6</ganados>
  <perdidos>4</perdidos>
  <empatados>12</empatados>
  <puntos>30</puntos>
</equipo>
<equipo>
  <nombre>Real Sociedad</nombre>
  <ganados>8</ganados>
  <perdidos>6</perdidos>
  <empatados>8</empatados>
  <puntos>30</puntos>
</equipo>
<equipo>
  <nombre>Eibar</nombre>
  <ganados>7</ganados>
  <perdidos>7</perdidos>
  <empatados>8</empatados>
  <puntos>29</puntos>
</equipo>
<equipo>
  <nombre>Levante</nombre>
  <ganados>7</ganados>
  <perdidos>9</perdidos>
  <empatados>6</empatados>
  <puntos>27</puntos>
</equipo>
<equipo>
  <nombre>ATH Bilbao</nombre>
  <ganados>5</ganados>
  <perdidos>6</perdidos>
  <empatados>11</empatados>
  <puntos>26</puntos>
</equipo>
<equipo>
  <nombre>Leganes</nombre>
  <ganados>6</ganados>
  <perdidos>8</perdidos>
  <empatados>8</empatados>
  <puntos>26</puntos>
</equipo>
<equipo>
  <nombre>Valladolid</nombre>
  <ganados>6</ganados>
  <perdidos>9</perdidos>
  <empatados>7</empatados>
  <puntos>25</puntos>
</equipo>
<equipo>
  <nombre>Español</nombre>
  <ganados>7</ganados>
  <perdidos>11</perdidos>
  <empatados>4</empatados>
  <puntos>25</puntos>
</equipo>
<equipo>
  <nombre>Celta</nombre>
  <ganados>6</ganados>
  <perdidos>10</perdidos>
  <empatados>6</empatados>
  <puntos>24</puntos>
</equipo>
<equipo>
  <nombre>Girona</nombre>
  <ganados>5</ganados>
  <perdidos>8</perdidos>
  <empatados>9</empatados>
  <puntos>24</puntos>
</equipo>
<equipo>
  <nombre>Rayo Vallecano</nombre>
  <ganados>6</ganados>
  <perdidos>11</perdidos>
  <empatados>5</empatados>
  <puntos>23</puntos>
</equipo>
<equipo>
  <nombre>Villareal</nombre>
  <ganados>3</ganados>
  <perdidos>9</perdidos>
  <empatados>10</empatados>
  <puntos>19</puntos>
</equipo>
<equipo>
  <nombre>Huesca</nombre>
  <ganados>3</ganados>
  <perdidos>13</perdidos>
  <empatados>6</empatados>
  <puntos>15</puntos>
</equipo>
</equipos>
